const PRODUCTS = [
  { id: 1, name: "Gaming Laptop", category: "Laptop", price: 999, oldPrice: 1199, rating: 4.8, reviews: 128, image: "laptop.jpg", description: "High-performance laptop for gaming, programming, editing and everyday work.", features: ["Intel Core i7 Processor", "16GB RAM", "512GB SSD", "RTX Graphics", "Full HD Display"] },
  { id: 2, name: "Smart Phone", category: "Mobile", price: 699, oldPrice: 799, rating: 4.6, reviews: 214, image: "mobile.jpg", description: "A modern smartphone designed for performance, photography, entertainment and productivity.", features: ["High-resolution display", "Fast processor", "All-day battery", "Advanced camera", "5G connectivity"] },
  { id: 3, name: "Smart Watch", category: "Watch", price: 249, oldPrice: 299, rating: 4.5, reviews: 96, image: "watch.jpg", description: "A stylish smartwatch for fitness tracking, notifications and everyday convenience.", features: ["Fitness tracking", "Heart-rate monitoring", "Smart notifications", "Long battery life", "Water resistant"] },
  { id: 4, name: "Wireless Headphones", category: "Headphones", price: 129, oldPrice: 159, rating: 4.7, reviews: 176, image: "headphones.jpg", description: "Comfortable wireless headphones with clear sound for music, calls, study and entertainment.", features: ["Wireless connectivity", "Clear audio", "Built-in microphone", "Comfortable cushions", "Long battery life"] },
  { id: 5, name: "Business Laptop", category: "Laptop", price: 899, oldPrice: 999, rating: 4.5, reviews: 84, image: "laptop.jpg", description: "A reliable laptop for professional work, software development and multitasking.", features: ["Fast processor", "16GB RAM", "512GB SSD", "Full HD display", "Professional design"] },
  { id: 6, name: "Flagship Mobile", category: "Mobile", price: 799, oldPrice: 899, rating: 4.7, reviews: 143, image: "mobile.jpg", description: "A premium smartphone combining strong performance, camera capabilities and modern design.", features: ["Premium display", "Powerful processor", "Advanced camera", "Fast charging", "5G connectivity"] },
  { id: 7, name: "Fitness Watch", category: "Watch", price: 199, oldPrice: 249, rating: 4.4, reviews: 72, image: "watch.jpg", description: "A fitness-focused smartwatch for tracking activity and staying connected throughout the day.", features: ["Activity tracking", "Workout modes", "Heart-rate monitoring", "Smart notifications", "Water resistant"] },
  { id: 8, name: "Bluetooth Headphones", category: "Headphones", price: 149, oldPrice: 179, rating: 4.6, reviews: 119, image: "headphones.jpg", description: "Wireless headphones built for comfortable listening at home, work and on the go.", features: ["Bluetooth connectivity", "Rich sound", "Built-in microphone", "Comfortable fit", "Long battery life"] }
];
